### ISSUE TITLE
Replace WTFPL License by any other open license (Apache 2.0, ISC, MIT)

### ISSUE THREAD

**Issue by better-call-alex-soul** [parshap/truncate-utf8-bytes#2]
It would be really great to replace WTFPL license from published npm artifacts

**Comment by benlangfeld** [comment]
@parshap Is this something you'd be willing to do? Can we do MIT or BSD or some other license that is already broadly acceptable to employers?

**Comment by parshap** [comment]
Sure. Would you like to send a PR? I would prefer "WTFPL OR MIT" to remain backwards compatible.
